name: Deploy website on push
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Verify install and build
      - run: npm ci && npm run build

      - name: Ssh into server and run deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/jungletech/
            sudo git pull origin main
            sudo npm install
            sudo npm run build
            sudo pm2 restart nextapp
